# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 34997a3681cbf8e382588065eac92725798ab8d39cea331b9f8abcb8c140f7659904194a525ee9be5724c9f77207f3240d70c9c5c5aa60bca263ed2251846ced

test:
  secret_key_base: 65b59aa8d75f2c4a6c8661fd94c6d7447543b12bf61a60cb1888459f79e6a8efe34545d4c5b9641d183ffe1d0426fd261a6af76ad0910dc6b656f313f98eb1f1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
